# Generated by Django 4.0.4 on 2022-07-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='roll',
        ),
        migrations.AddField(
            model_name='productdetails',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
